CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(512) NOT NULL,
    event_id BIGINT NOT NULL,
    author_id  BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
    );

CREATE TABLE IF NOT EXISTS comments_likes(
    comment_id BIGINT REFERENCES comments(comment_id) ON DELETE CASCADE,
    user_id BIGINT,
    PRIMARY KEY (comment_id, user_id)
    );

CREATE TABLE IF NOT EXISTS ban_comments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT,
    user_id BIGINT,
    CONSTRAINT unique_event_user UNIQUE (event_id, user_id)
    );