server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6433/ewm-main
    username: root
    password: root
  sql:
    init:
      mode: always

feign:
  circuitbreaker:
    enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 1
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 1
      automaticTransitionFromOpenToHalfOpenEnabled: true

grpc:
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext