spring:
  application:
    name: request-service
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
      discovery:
        enabled: true
        serviceId: config-server
  datasource:
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    preferIpAddress: true