spring:
  application:
    name: gateway-server
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server
logging:
  level:
    root: DEBUG
    org.springframework.web: TRACE
    org.springframework.cloud: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    feign: DEBUG
    com.netflix.discovery: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10