server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: main-service-route
          uri: lb://main-service
          predicates:
            - Path=/**