server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin_category
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**

        - id: public_category
          uri: lb://event-service
          predicates:
            - Path=/categories/**

        - id: admin_compilation
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**

        - id: public_compilation
          uri: lb://event-service
          predicates:
            - Path=/compilations/**

        - id: admin_event
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**

        - id: private_event
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events/**

        - id: public_event
          uri: lb://event-service
          predicates:
            - Path=/events/**

        - id: participation_request
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/requests/**

        - id: user
          uri: lb://event-service
          predicates:
            - Path=/admin/users/**