server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: main-service-route
          uri: lb://main-service
          predicates:
            - Path=/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: [ NOT_FOUND ]
                methods: [ GET ]