grpc:
  server:
    port: 9091
    security:
      enabled: false
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show_sql: true

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:6432/ewm-stats
    username: root
    password: root

  kafka:
    bootstrap-server: localhost:9092
    consumer:
      user-action-client-id: UserActionClient
      user-action-group-id: UserActionGroup.Analyzer
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: ru.practicum.ewm.deserializer.UserActionDeserializer
      enable-auto-commit: false
      poll-timeout: 1000
      similarity-client-id: SimilarityClient
      similarity-group-id: SimilarityGroup
      similarity-deserializer: ru.practicum.ewm.deserializer.EventSimilarityDeserializer

analyzer:
  topic:
    user-action: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

application:
  action-weight:
    view: 0.4
    register: 0.8
    like: 1.0